#!/bin/sh

exec docker run \
    --rm \
    --tty \
    --interactive \
    --device=/dev/net/tun \
    --name=ovpn2socks \
    --cap-add=NET_ADMIN \
    --publish 1080:1080 \
    --volume "$(realpath "$1"):/ovpn.conf:ro" \
    zenexas/openvpn-client-socks
